eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


server:
  port: 8000
spring:
  application:
    name: bussiness-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata-bussiness?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    password: root
    username: root

