server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  instance:
    appname: provider-service
    hostname: localhost
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
spring:
  main:
    allow-bean-definition-overriding: true